// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/coffee.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoParam) Reset() {
	*x = NoParam{}
	mi := &file_proto_coffee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParam) ProtoMessage() {}

func (x *NoParam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParam.ProtoReflect.Descriptor instead.
func (*NoParam) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{0}
}

type Menu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Items               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Menu) Reset() {
	*x = Menu{}
	mi := &file_proto_coffee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Menu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Menu) ProtoMessage() {}

func (x *Menu) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Menu.ProtoReflect.Descriptor instead.
func (*Menu) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{1}
}

func (x *Menu) GetItem() []*Items {
	if x != nil {
		return x.Item
	}
	return nil
}

type Items struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Items) Reset() {
	*x = Items{}
	mi := &file_proto_coffee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Items) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Items) ProtoMessage() {}

func (x *Items) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Items.ProtoReflect.Descriptor instead.
func (*Items) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{2}
}

func (x *Items) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Items) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          []*Items               `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_proto_coffee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{3}
}

func (x *Order) GetItem() []*Items {
	if x != nil {
		return x.Item
	}
	return nil
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_proto_coffee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{4}
}

func (x *Receipt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatus) Reset() {
	*x = OrderStatus{}
	mi := &file_proto_coffee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatus) ProtoMessage() {}

func (x *OrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coffee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatus.ProtoReflect.Descriptor instead.
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return file_proto_coffee_proto_rawDescGZIP(), []int{5}
}

func (x *OrderStatus) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_coffee_proto protoreflect.FileDescriptor

const file_proto_coffee_proto_rawDesc = "" +
	"\n" +
	"\x12proto/coffee.proto\x12\x05proto\"\t\n" +
	"\aNoParam\"(\n" +
	"\x04Menu\x12 \n" +
	"\x04item\x18\x01 \x03(\v2\f.proto.ItemsR\x04item\"+\n" +
	"\x05Items\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\")\n" +
	"\x05Order\x12 \n" +
	"\x04item\x18\x01 \x03(\v2\f.proto.ItemsR\x04item\"\x19\n" +
	"\aReceipt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\vOrderStatus\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\x98\x01\n" +
	"\n" +
	"CoffeeShop\x12(\n" +
	"\aGetMenu\x12\x0e.proto.NoParam\x1a\v.proto.Menu0\x01\x12*\n" +
	"\n" +
	"PlaceOrder\x12\f.proto.Order\x1a\x0e.proto.Receipt\x124\n" +
	"\x0eGetOrderStatus\x12\x0e.proto.Receipt\x1a\x12.proto.OrderStatusB\x19Z\x17go-grpc-coffeshop/protob\x06proto3"

var (
	file_proto_coffee_proto_rawDescOnce sync.Once
	file_proto_coffee_proto_rawDescData []byte
)

func file_proto_coffee_proto_rawDescGZIP() []byte {
	file_proto_coffee_proto_rawDescOnce.Do(func() {
		file_proto_coffee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coffee_proto_rawDesc), len(file_proto_coffee_proto_rawDesc)))
	})
	return file_proto_coffee_proto_rawDescData
}

var file_proto_coffee_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_coffee_proto_goTypes = []any{
	(*NoParam)(nil),     // 0: proto.NoParam
	(*Menu)(nil),        // 1: proto.Menu
	(*Items)(nil),       // 2: proto.Items
	(*Order)(nil),       // 3: proto.Order
	(*Receipt)(nil),     // 4: proto.Receipt
	(*OrderStatus)(nil), // 5: proto.OrderStatus
}
var file_proto_coffee_proto_depIdxs = []int32{
	2, // 0: proto.Menu.item:type_name -> proto.Items
	2, // 1: proto.Order.item:type_name -> proto.Items
	0, // 2: proto.CoffeeShop.GetMenu:input_type -> proto.NoParam
	3, // 3: proto.CoffeeShop.PlaceOrder:input_type -> proto.Order
	4, // 4: proto.CoffeeShop.GetOrderStatus:input_type -> proto.Receipt
	1, // 5: proto.CoffeeShop.GetMenu:output_type -> proto.Menu
	4, // 6: proto.CoffeeShop.PlaceOrder:output_type -> proto.Receipt
	5, // 7: proto.CoffeeShop.GetOrderStatus:output_type -> proto.OrderStatus
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_coffee_proto_init() }
func file_proto_coffee_proto_init() {
	if File_proto_coffee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coffee_proto_rawDesc), len(file_proto_coffee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coffee_proto_goTypes,
		DependencyIndexes: file_proto_coffee_proto_depIdxs,
		MessageInfos:      file_proto_coffee_proto_msgTypes,
	}.Build()
	File_proto_coffee_proto = out.File
	file_proto_coffee_proto_goTypes = nil
	file_proto_coffee_proto_depIdxs = nil
}
